# Generated by Django 4.0 on 2021-12-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishilists',
            field=models.ManyToManyField(related_name='shopper', to='restaurants.Restaurant'),
        ),
    ]
