# Generated by Django 4.0 on 2021-12-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_cart_quantity'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='carts',
            field=models.ManyToManyField(related_name='menu', to='payments.Cart'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_types',
            field=models.ManyToManyField(related_name='group_menu', to='reviews.MenuType'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='options',
            field=models.ManyToManyField(related_name='extra_menu', to='reviews.Option'),
        ),
    ]
