# Generated by Django 4.0 on 2021-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_menu_carts_alter_menu_menu_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
