# Generated by Django 4.0 on 2022-01-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_category'),
        ('reviews', '0006_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
